"""Expand the reviewed dependency closure into a hash-pinned lock file.

SEC-005 is about the operator workstation: any third-party tree installed there
lands on the highest-privilege boundary in the system, inside the component that
computes the scope-contract hash. Hash pinning is what makes an install
reproducible rather than merely repeatable.

Resolution is a reviewed act, not an automatic one. The closure lives in
supply-chain.json with a recorded reason per package, and this tool only expands
it into hashes. A generator that also resolved would let a new transitive
dependency enter the tree without anyone deciding to admit it, which is the
thing the review exists to prevent.

Only wheels are recorded. A source distribution executes its build at install
time, which is exactly the arbitrary code execution ADR-0004 rules out.

Network access is used here, at authoring time. Nothing in the validation path
ever calls this, and --verify runs offline.
"""

import argparse
import json
import os
import sys
import urllib.request

PYPI_URL = "https://pypi.org/pypi/%s/%s/json"

EXIT_OK = 0
EXIT_FAILED = 1

HEADER = """\
# Generated by tools/supply_chain/generate_lock.py from tools/supply-chain.json.
# Do not edit by hand: a hand-edited hash is indistinguishable from a tampered one.
#
# Install with, and only with:
#   python -m pip install --require-hashes --only-binary=:all: -r tools/requirements.lock
#
# --require-hashes makes pip refuse anything whose hash is not listed here.
# --only-binary=:all: makes pip refuse a source distribution, which would run a
# build at install time. Dropping either flag silently removes the control.
#
# The zeroops package itself is deliberately NOT installed. The bin/ shims put
# tools/ on PYTHONPATH, so the only third-party code entering the workstation is
# the closure below.
#
# Interpreter floor: Python {floor}
# Closure: {count} package(s), reviewed in tools/supply-chain.json
"""


class LockError(Exception):
    """The lock could not be generated."""


def _lower_bound(specifier):
    """Return the (major, minor) floor a `>=X.Y` specifier imposes.

    Only the `>=` form is understood. Anything else raises, because a specifier
    this cannot read must not be silently treated as imposing no floor: that is
    how a package that requires a newer interpreter slips past the check.
    """
    text = (specifier or "").strip()
    if not text.startswith(">="):
        raise LockError(
            "cannot read the python requirement %r. Only the '>=X.Y' form is "
            "understood; a specifier this cannot read must not be treated as "
            "imposing no floor." % specifier
        )
    parts = text[2:].strip().split(".")
    try:
        return int(parts[0]), int(parts[1]) if len(parts) > 1 else 0
    except (ValueError, IndexError):
        raise LockError("cannot read the python requirement %r" % specifier)


def interpreter_floor_problems(declaration):
    """Report packages that require a newer interpreter than the declared floor.

    This is the check that catches the floor being chosen rather than derived.
    It runs offline against the reviewed requires_python values, so a wrong
    floor fails in CI instead of failing at install time on a contributor's
    machine.
    """
    problems = []
    try:
        floor = _lower_bound(">=" + declaration["interpreterFloor"])
    except LockError as exc:
        return [str(exc)]

    for package in declaration["packages"]:
        try:
            required = _lower_bound(package.get("requiresPython"))
        except LockError as exc:
            problems.append("%s: %s" % (package["name"], exc))
            continue
        if required > floor:
            problems.append(
                "%s requires Python %s but the declared floor is %s. The floor is "
                "set by the strictest member of the closure, not chosen; raise it "
                "to %d.%d."
                % (
                    package["name"],
                    package["requiresPython"],
                    declaration["interpreterFloor"],
                    required[0],
                    required[1],
                )
            )
    return problems


def tools_dir():
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def declaration_path():
    return os.path.join(tools_dir(), "supply-chain.json")


def lock_path():
    return os.path.join(tools_dir(), "requirements.lock")


def load_declaration():
    with open(declaration_path(), "r", encoding="utf-8") as handle:
        return json.load(handle)


def _wheel_tags(filename):
    """Return (python_tag, platform_tag) from a wheel filename."""
    stem = filename[: -len(".whl")]
    parts = stem.split("-")
    return parts[-3], parts[-1]


def select_wheels(release_urls, declaration):
    """Choose the wheels this project supports, and no others."""
    python_tags = set(declaration["pythonTags"])
    platform_tags = set(declaration["platformTags"])

    selected = []
    for entry in release_urls:
        if entry["packagetype"] != "bdist_wheel":
            continue
        python_tag, platform_tag = _wheel_tags(entry["filename"])

        if platform_tag == "any" and python_tag.startswith("py3"):
            selected.append(entry)
            continue
        if python_tag in python_tags and platform_tag in platform_tags:
            selected.append(entry)
    return selected


def fetch_release(name, version):
    with urllib.request.urlopen(PYPI_URL % (name, version), timeout=60) as response:
        return json.load(response)


def generate(declaration):
    floor_problems = interpreter_floor_problems(declaration)
    if floor_problems:
        raise LockError(
            "the declared interpreter floor does not hold:\n  " + "\n  ".join(floor_problems)
        )

    lines = []
    summary = []
    for package in declaration["packages"]:
        name = package["name"]
        version = package["version"]
        release = fetch_release(name, version)

        requires_python = release["info"].get("requires_python") or ""
        if requires_python != package.get("requiresPython"):
            raise LockError(
                "%s==%s: PyPI declares requires_python %r but supply-chain.json "
                "records %r. The recorded value is what the offline floor check "
                "reads, so it must be corrected through review before the lock is "
                "regenerated."
                % (name, version, requires_python, package.get("requiresPython"))
            )

        wheels = select_wheels(release["urls"], declaration)
        if not wheels:
            raise LockError(
                "%s==%s: no wheel matches the supported python and platform tags. "
                "Either the package ships no wheel for a platform this project "
                "claims to support, or the tag lists in supply-chain.json are "
                "wrong. Falling back to a source distribution is not an option."
                % (name, version)
            )

        digests = []
        for wheel in sorted(wheels, key=lambda w: w["filename"]):
            sha256 = wheel["digests"]["sha256"]
            if len(sha256) != 64:
                raise LockError("%s: malformed sha256 for %s" % (name, wheel["filename"]))
            digests.append(sha256)

        lines.append("%s==%s \\" % (name, version))
        for index, digest in enumerate(digests):
            terminator = "" if index == len(digests) - 1 else " \\"
            lines.append("    --hash=sha256:%s%s" % (digest, terminator))

        summary.append((name, version, len(digests), requires_python, package["role"]))

    header = HEADER.format(
        floor=declaration["interpreterFloor"], count=len(declaration["packages"])
    )
    return header + "\n" + "\n".join(lines) + "\n", summary


def write_lock(declaration):
    body, summary = generate(declaration)
    with open(lock_path(), "w", encoding="utf-8", newline="\n") as handle:
        handle.write(body)
    return summary


def parse_lock(text):
    """Return {name: (version, [hashes])} from a requirements lock."""
    pinned = {}
    current = None
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("--hash="):
            if current is None:
                raise LockError("a hash appears before any requirement")
            pinned[current][1].append(stripped.rstrip("\\").strip()[len("--hash=") :])
            continue
        requirement = stripped.rstrip("\\").strip()
        if "==" in requirement:
            name, version = requirement.split("==", 1)
            current = name.strip()
            pinned[current] = (version.strip(), [])
    return pinned


def verify_lock(declaration, lock_file=None):
    """Report the ways the committed lock could disagree with the declaration.

    `lock_file` is injectable so the suite can show these checks rejecting a bad
    lock. A verifier only ever observed to pass is not known to verify anything.
    """
    path = lock_file or lock_path()
    if not os.path.isfile(path):
        return ["%s is missing; nothing pins the dependency tree." % path]

    with open(path, "r", encoding="utf-8") as handle:
        text = handle.read()

    problems = list(interpreter_floor_problems(declaration))
    try:
        pinned = parse_lock(text)
    except LockError as exc:
        return problems + [str(exc)]
    declared = {p["name"]: p["version"] for p in declaration["packages"]}

    for name, version in declared.items():
        if name not in pinned:
            problems.append(
                "%s is reviewed in supply-chain.json but absent from the lock." % name
            )
        elif pinned[name][0] != version:
            problems.append(
                "%s: reviewed as %s, pinned as %s. Regenerate the lock, or admit "
                "the new version through review first." % (name, version, pinned[name][0])
            )

    for name in pinned:
        if name not in declared:
            problems.append(
                "%s is pinned in the lock but was never reviewed. A dependency that "
                "entered without a decision is what this file exists to stop." % name
            )

    for name, (_version, hashes) in pinned.items():
        if not hashes:
            problems.append(
                "%s carries no hash, so --require-hashes would reject the whole file "
                "and an operator would be tempted to drop the flag." % name
            )
        for digest in hashes:
            if not digest.startswith("sha256:") or len(digest) != len("sha256:") + 64:
                problems.append("%s: malformed hash entry %r" % (name, digest))

    return problems


def main(argv=None):
    parser = argparse.ArgumentParser(
        prog="generate_lock",
        description="Expand the reviewed dependency closure into a hash-pinned lock.",
    )
    parser.add_argument(
        "--verify",
        action="store_true",
        help="Check the committed lock against the declaration. Runs offline.",
    )
    parser.add_argument(
        "--lock",
        default=None,
        help="Lock file to verify. Defaults to tools/requirements.lock.",
    )
    args = parser.parse_args(argv)

    declaration = load_declaration()

    if args.verify:
        problems = verify_lock(declaration, lock_file=args.lock)
        if problems:
            sys.stderr.write("Supply chain lock does not hold:\n")
            for problem in problems:
                sys.stderr.write("  %s\n" % problem)
            return EXIT_FAILED
        sys.stdout.write("Supply chain lock holds.\n")
        return EXIT_OK

    try:
        summary = write_lock(declaration)
    except LockError as exc:
        sys.stderr.write("error: %s\n" % exc)
        return EXIT_FAILED

    sys.stdout.write("Wrote %s\n" % lock_path())
    for name, version, count, requires_python, role in summary:
        sys.stdout.write(
            "  %-26s %-12s %-11s %3d wheel hash(es)  requires_python=%s\n"
            % (name, version, role, count, requires_python or "unset")
        )
    return EXIT_OK


if __name__ == "__main__":
    sys.exit(main())
